### ISSUE TITLE
launchファイルのrosparmを動的な変数で指定したい

### ISSUE THREAD

**Issue by shmpwk** [shmpwk/jsk_2020_04_carry_dish#7]
launchファイル内でrosparamに変数を渡したいです。

例えば、[DepthImageCreator](https://jsk-docs.readthedocs.io/projects/jsk_recognition/en/latest/jsk_pcl_ros/nodes/depth_image_creator.html?highlight=depth%20image%20creater)では、param指定に
```
~translation (Array of double, default: [0, 0, 0])
~rotation (Array of double, default: [0, 0, 0, 1])
```
とあります。これを例えば、カメラ座標と対象物体座標のtf座標変換に置き換えたいと考えています。

一つの方法としては、tf座標変換をまずyamlファイルに保存して、それを`<rosparam command="load" file="$(find rosparam)/example.yaml" />`のようにして読み込むことだと思います。([参考](http://wiki.ros.org/roslaunch/XML/rosparam)).
しかし、もう少しスマートな方法はないかなと探しています。

launchファイルでなければ、コマンドラインで`$ rosparam get `とすればパラメータサーバーから変数を受け取れると思うのですが、、、

**Comment by shmpwk** [comment]
launchするnode scriptをdynamic reconfigureで直接いじるという方法もありますかね。

**Comment by pazeshun** [comment]
パラメーターを外部から動的に設定できるようにするのがdynamic reconfigureだから、使いたいnodeがdynamic reconfigure化されていたら、それを使って解決だけど、使いたいnodeがdynamic reconfigure化されてないから面倒、ってことでしょうか。

**Comment by pazeshun** [comment]
どうするかは場合によると思いますが、DepthImageCreatorが使いたいんだったら、そもそも仮想カメラのcamera_infoを入力にして、その仮想カメラの位置姿勢を自由に動かしたらよいだけではないのでしょうか。translationやrotationはuse_fixed_transformがtrueの時だけ有効ですが、デフォルトがfalseなのは、普通カメラの方を動かすからでは？

**Comment by shmpwk** [comment]
はい、使いたいノードがdynamic reconfigureではなさそうです。
例えば、上で例として上げた[depth_image_creator_nodelet.cpp](https://github.com/jsk-ros-pkg/jsk_recognition/blob/7fe6e1f22cceef4c33a64f128e36ef71c4f29bac/jsk_pcl_ros/src/depth_image_creator_nodelet.cpp)と[そのヘッダー](https://github.com/jsk-ros-pkg/jsk_recognition/blob/7fe6e1f22cceef4c33a64f128e36ef71c4f29bac/jsk_pcl_ros/include/jsk_pcl_ros/depth_image_creator.h)見ると、dynamic reconfigureを使っていないと思います。

**Comment by shmpwk** [comment]
depth image creatorの場合、仮想カメラの位置を動かす際に、対象物を基準に自由に動かすことができればそれで大丈夫です。

**Comment by kosuke55** [comment]
これがぱっと見仮想カメラの位置を動的に変えられるような気がします.
https://jsk-recognition.readthedocs.io/en/latest/jsk_perception/nodes/virtual_camera_mono.html

publishされるcamera_infoをDepthImageCreatorに渡してあげれば良いと思います.

**Comment by shmpwk** [comment]
リンクありがとうございます。これは便利ですね。ぜひ使います。

**Comment by shmpwk** [comment]
本題のissue自体は解決していませんが、回避できそうなので、closeします。
@kosuke55 @pazeshun 迅速なご回答ありがとうございました。

**Comment by kosuke55** [comment]
すみません、virtual_camera_monoでdynamic_reconfigureになってるのinterpolation_methodだけでしたよね。
やりたいことはtfをdynamic_reconfigureで変更することなので、何をつかっても良いのですが少し検索してみると
https://github.com/Flos/ros-tf2_dynamic
というものが見つかりました。
これで出したframeをhttps://jsk-recognition.readthedocs.io/en/latest/jsk_perception/nodes/image_publisher.html などで出力した仮想的なcamera_infoに与えてみると良いと思います。
![Screenshot from 2020-09-29 14-50-01](https://user-images.githubusercontent.com/39142679/94517573-38080680-0263-11eb-9133-48fe3fc6a031.png)

**Comment by shmpwk** [comment]
> virtual_camera_monoでdynamic_reconfigureになってるのinterpolation_methodだけでしたよね

tfに関しては、dynamic reconfigureではなく、rospramで作りだせるのかなと思っていました。

サンプルプログラムを真似して書いたものが[こちら](https://github.com/shmpwk/grasp_recognition/blob/master/launch/virtual_camera_mono.launch) です。

ただ、これもうまくいっておらず、[こちら](https://github.com/shmpwk/grasp_recognition/issues/4)でissueを立てています。

ということは、 @kosuke55 さんのようにtfを作る必要があったのかなと今思っています。

**Comment by kosuke55** [comment]
https://github.com/Flos/ros-tf2_dynamic を使ったdepth_image_creatorのサンプルも貼っときますね。
https://gist.github.com/kosuke55/4c6dc54b298cca1e27153cb56be6cc51

ちなみにfovは https://gist.github.com/kosuke55/4c6dc54b298cca1e27153cb56be6cc51#file-camera_ifno-yaml こんな感じにrosのcamera_infoを保存して、
https://github.com/iory/cameramodels で　
```
from cameramodels import PinholeCameraModel
cm = PinholeCameraModel.from_yaml_file('camera_info.yaml')
cm.fovx
cm.fovy
```
とすると計算できます。

**Comment by shmpwk** [comment]
ありがとうございます!  確認してみます。

**Comment by shmpwk** [comment]
仮想カメラの位置動かせそうです。ありがとうございます！

![202009292028](https://user-images.githubusercontent.com/42209144/94552743-51747700-0292-11eb-9de5-d6970a32335a.gif)
